force-app/main/default/objects/Assignment_Group__c/Assignment_Group__c.object-meta.xml
<CustomObject>
    <label>Assignment Group</label>
    <nameField>
        <label>Assignment Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Group__c</fullName>
    <label>Assignment Group</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Budget_Score__c.field-meta.xml
<CustomField>
    <fullName>Budget_Score__c</fullName>
    <formula>IF(Has_Budget__c = true, 5, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Budget Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Consultation_Fees__c.field-meta.xml
<CustomField>
    <fullName>Consultation_Fees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Consultation Fees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Discovery_Demo_Date__c.field-meta.xml
<CustomField>
    <fullName>Discovery_Demo_Date__c</fullName>
    <label>Discovery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Evaluation_Score__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Score__c</fullName>
    <label>Evaluation Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Evaluation_Score_V1__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Score_V1__c</fullName>
    <formula>Title_Job_Title_Score__c +  Qualification_Score__c +  Experience_Score__c + Ilets__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This is out of 25 and Any score greater that 15 is Eligible otherwise Not Eligible</inlineHelpText>
    <label>Evaluation Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Experience_Score__c.field-meta.xml
<CustomField>
    <fullName>Experience_Score__c</fullName>
    <formula>IF( Experience__c  == null ,0,6)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Maximum score can be 6</inlineHelpText>
    <label>Experience Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Follow_Up_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date_Time__c</fullName>
    <label>Follow Up Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Has_Budget__c.field-meta.xml
<CustomField>
    <fullName>Has_Budget__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Budget</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Ilets__c.field-meta.xml
<CustomField>
    <fullName>Ilets__c</fullName>
    <inlineHelpText>Maximum Score can be 9</inlineHelpText>
    <label>IELTS Score</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Assigned_Date__c.field-meta.xml
<CustomField>
    <fullName>Lead_Assigned_Date__c</fullName>
    <label>Lead Assigned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Assigned_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Assigned_Time__c</fullName>
    <label>Lead Assigned Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Capture_Date__c.field-meta.xml
<CustomField>
    <fullName>Lead_Capture_Date__c</fullName>
    <label>Lead Capture Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Substatus__c.field-meta.xml
<CustomField>
    <fullName>Lead_Substatus__c</fullName>
    <label>Lead Substatus</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Price To High</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>Called</fullName>
            </value>
            <value>
                <fullName>Connected</fullName>
            </value>
            <value>
                <fullName>Partial Eligible</fullName>
            </value>
            <value>
                <fullName>Request sent</fullName>
            </value>
            <value>
                <fullName>Details Received</fullName>
            </value>
            <value>
                <fullName>Requested Modification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Project_Defined_Score__c.field-meta.xml
<CustomField>
    <fullName>Project_Defined_Score__c</fullName>
    <formula>IF(  Project_Defined__c = true,5, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Defined Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Qualification_Score__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Score__c</fullName>
    <formula>If( Quantity__c == null ,0,5)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Maximum score can be 5</inlineHelpText>
    <label>Qualification Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TaskTriggerHandler.cls
public without sharing class TaskTriggerHandler {
   
    static TaskTriggerHandler taskhandlerInstance;

    public static TaskTriggerHandler getInstance(){
        if (taskhandlerInstance == null)
        taskhandlerInstance = new TaskTriggerHandler();
        return taskhandlerInstance;
    }

    public void convertLeadStatus(List<task> TaskNewlist){

        set<id> Leadids = new Set<Id>();
        map<id, task> TaskIdwithTask = new Map<Id, Task>();
        map<string, String> LeadIdWithTaskID = new Map<String, string>();
        List<Lead> UpdatedLeadList = new List<Lead>();
        List<lead> LeadListQueried = new List<Lead>();




        try {
            if (!TaskNewlist.isEmpty()) {
                for (task tsk : TaskNewlist) {
                    if (tsk.Call_Unique_Identifier__c != null && tsk.Call_conversation_Duration__c !=  null  ) {
                        Leadids.add(tsk.whoid);
                        TaskIdwithTask.put(tsk.Id, tsk);
                        LeadIdWithTaskID.put(tsk.whoid, tsk.Id);
                    }
                }

                if (!Leadids.isEmpty() && Leadids.size() >0) {
                    LeadListQueried = [SELECT Assignment_Group__c,Budget_Score__c,City,Company,Consultation_Fees__c,Country,Designation__c,Discovery_Demo_Date__c,Email,Evaluation_Score_V1__c,Evaluation_Score__c,Experience_Score__c,Experience__c,Follow_Up_Date_Time__c,Has_Budget__c,Ilets__c,Lead_Assigned_Date__c,Lead_Assigned_Time__c,Lead_Capture_Date__c,Lead_Substatus__c,Name,Product__c,Project_Defined_Score__c,Project_Defined__c,Qualification_Score__c, Quantity__c 
                                        FROM Lead 
                                        where Id IN: Leadids];
                    
                    if (!LeadListQueried.isEmpty()) {

                        for (Lead ld : LeadListQueried) {
                            if (ld.status == Constants.LEAD_STATUS_NEW) {
                                ld.Status = Constants.LEAD_STATUS_CONTACTED;
                                ld.Lead_Substatus__c = Constants.LEAD_SUBSTATUS_CONNECTED;
                                UpdatedLeadList.add(ld);
                                
                            }
                        }
                    }
                    if (!UpdatedLeadList.isEmpty()) {
                        update UpdatedLeadList;
                        //EmailIUtility.SendProcessEmail(UpdatedLeadList);

                    }
                    
                }
                
            }

        } catch (Exception e) {
            System.debug('the error has occured due to ====> ' + e.getMessage());
            System.debug('The error has occured at line number ======> ' + e.getLineNumber());
            HandleBusinessException.captureError('LeadTriggerHandler', 'Createtask', e, null);
        }

    }

}