force-app/main/default/objects/Exceptions__c/Exceptions__c.object-meta.xml
<CustomObject>
    <label>Exceptions</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Exception No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exceptions__c/fields/API_JSON_body__c.field-meta.xml
<CustomField>
    <fullName>API_JSON_body__c</fullName>
    <label>API JSON body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Exceptions__c/fields/Error_Line_No__c.field-meta.xml
<CustomField>
    <fullName>Error_Line_No__c</fullName>
    <label>Error Line No.</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exceptions__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Exceptions__c/fields/Error_Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Error_Stack_Trace__c</fullName>
    <label>Error Stack Trace</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Exceptions__c/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <label>Error Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HandleBusinessException.cls
/* 
* @Description : This class is used to capture exception in custom object.
* 				 Note: This class/method should not be used if try/catch is inside a loop. 
* 				 As insert in not bulyfy in insertError method.
*Author : DeaGle~       
*/ 
public class HandleBusinessException extends Exception {
    
    public static void captureError(String className, String methodName, Exception ex, string JSONbody){
        //string JSONbody = '';
        Exceptions__c newException = createError(className, methodName, ex, JSONbody);
        insertError(newException);          
    }
    
 private static Exceptions__c createError(String className, String methodName, Exception ex, String JSONbody){
        Exceptions__c result 		= new Exceptions__c();
        result.Class_Name__c 		= className;
        result.Method_Name__c 		= methodName;
        result.Error_Message__c 	= ex.getMessage();
        result.Error_Stack_Trace__c	= ex.getStackTraceString();
        result.Error_Line_No__c		= ex.getLineNumber();
        result.Error_Type__c		= ex.getTypeName();
        if (JSONbody != null) {
            result.API_JSON_body__c = JSONbody;
        }
            
        return result;
    }
    
  private static void insertError(Exceptions__c exceps){
        try{
            Database.SaveResult lsr = Database.insert(exceps, false);
            if (lsr.isSuccess()) {
                EmailIUtility.sendExceptions(exceps);
            }
        }
        catch(DMLException dmlError){}
    }
}