force-app/main/default/objects/Explorer_Configuration__c/Explorer_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Explorer Configuration</label>
</CustomObject>

force-app/main/default/objects/Explorer_Configuration__c/fields/Folders__c.field-meta.xml
<CustomField>
    <fullName>Folders__c</fullName>
    <label>Folders</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Folder__c/Folder__c.object-meta.xml
<CustomObject>
    <label>Folder</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Folder__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Folders</relationshipLabel>
    <relationshipName>Folders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTriggerDMSHandler.cls
public class LeadTriggerDMSHandler {
    static LeadTriggerDMSHandler leadTriggerHandler;
    public static LeadTriggerDMSHandler getInstance(){
        if(leadTriggerHandler==null)
            leadTriggerHandler = new LeadTriggerDMSHandler();
        return leadTriggerHandler;
    }
    
    
    public void afterInsert(Map<Id,Lead> leadMap){
        System.debug('RUN--'+leadMap);
        Explorer_Configuration__c  leDocConfig = Explorer_Configuration__c.getValues('Lead');
        String accFoldersString = leDocConfig.Folders__c;
        
        List<String> leadFolders = accFoldersString.split(';');
        System.debug('Folder Selected---'+leadFolders);
        
        List<Folder__c> folders = new List<Folder__c>();
        
        for(Lead le : leadMap.values()){
            for(String fName : leadFolders){
                Folder__c folder = new Folder__c(Name=fName,Lead__c = le.Id);
                folders.add(folder);
            }
        }
        
        if(!folders.isEmpty()){
         	insert folders;   
        }
    }

}