force-app/main/default/objects/Explorer_Configuration__c/Explorer_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Explorer Configuration</label>
</CustomObject>

force-app/main/default/objects/Explorer_Configuration__c/fields/Folders__c.field-meta.xml
<CustomField>
    <fullName>Folders__c</fullName>
    <label>Folders</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Folder__c/Folder__c.object-meta.xml
<CustomObject>
    <label>Folder</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Folder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Folders</relationshipLabel>
    <relationshipName>Folders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public class AccountTriggerHandler {
	static AccountTriggerHandler accTriggerHandler;
    public static AccountTriggerHandler getInstance(){
        if(accTriggerHandler==null)
            accTriggerHandler = new AccountTriggerHandler();
        return accTriggerHandler;
    }
    
    
    public void afterInsert(Map<Id,Account> accMap){
        Explorer_Configuration__c  accDocConfig = Explorer_Configuration__c.getValues('Account');
        String accFoldersString = accDocConfig.Folders__c;
        
        List<String> accFolders = accFoldersString.split(';');
        
        List<Folder__c> folders = new List<Folder__c>();
        
        for(Account acc : accMap.values()){
            for(String fName : accFolders){
                Folder__c folder = new Folder__c(Name=fName, Account__c = acc.Id);
                folders.add(folder);
            }
        }
        
        if(!folders.isEmpty()){
         	insert folders; 
        }
    }
}