force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
                <default>true</default>
                <label>Gold</label>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Processing_Stage__c.field-meta.xml
<CustomField>
    <fullName>Processing_Stage__c</fullName>
    <label>Processing Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultation Completed</fullName>
                <default>true</default>
                <label>Consultation Completed</label>
            </value>
            <value>
                <fullName>Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>Document Verified</fullName>
            </value>
            <value>
                <fullName>Visa Initiated</fullName>
            </value>
            <value>
                <fullName>Visa Finalized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountSummamryModel.cls
public class AccountSummamryModel {

    static AccountSummamryModel accSummaryInstance;

    public static AccountSummamryModel getInstance(){
        if(accSummaryInstance==null)
            accSummaryInstance = new AccountSummamryModel();
        return accSummaryInstance;
    }

	public Account getAccountRecords(String accId){
        return [select Id,Name,AccountNumber,Rating,Website,Processing_Stage__c,Type,Industry,Account_Type__c,Phone,Email__c,
        (Select id,Firstname,Lastname,Email,Phone from Contacts),
        (Select id,StageName,Closedate,Amount from Opportunities),
        (Select id,Status,Subject,Priority from Cases)
        from Account where id=:accId];
    }
	public List<Account> getAllAccountRecords(){
    	return [select Id,Name,AccountNumber,Rating,Website,
            (Select id,Firstname,lastname,Email,Phone from Contacts),
            (Select id,StageName,Closedate,Amount from Opportunities),
            (Select id,Status,Subject,Priority from Cases)
            from Account];
    }

    public Lead getLeadRecord(String recId){
        return [Select Id,Name,Phone,Email,Company,Title,Designation__c,status,(Select id,Status,Subject,Priority from Cases__r) From Lead Where Id=:recId];
    }
}