force-app/main/default/objects/Account/fields/GSTIN__c.field-meta.xml
<CustomField>
    <fullName>GSTIN__c</fullName>
    <label>GSTIN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Specifications__c/Company_Specifications__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Company Specifications</label>
</CustomObject>

force-app/main/default/objects/Company_Specifications__c/fields/CGST_Rate__c.field-meta.xml
<CustomField>
    <fullName>CGST_Rate__c</fullName>
    <label>CGST  Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Company_Specifications__c/fields/Corporate_Identity__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Identity__c</fullName>
    <label>Corporate Identity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Specifications__c/fields/GSTIN__c.field-meta.xml
<CustomField>
    <fullName>GSTIN__c</fullName>
    <label>GSTIN</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Specifications__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>233</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Specifications__c/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <label>PAN</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Specifications__c/fields/Sac_Code__c.field-meta.xml
<CustomField>
    <fullName>Sac_Code__c</fullName>
    <label>Sac Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Specifications__c/fields/SGST_Rate__c.field-meta.xml
<CustomField>
    <fullName>SGST_Rate__c</fullName>
    <label>SGST Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/LeadInvoice__c.field-meta.xml
<CustomField>
    <fullName>LeadInvoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Consultation_Fees__c.field-meta.xml
<CustomField>
    <fullName>Consultation_Fees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Consultation Fees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CroyezInvoicePDF.cls
public class CroyezInvoicePDF {
    
    public Company_Specifications__c customSettingRec {get; set;} 
    public Invoice__c inoviceRec {get; set;} 
    public Opportunity oppRec {get; set;} 
    public string name {get; set;} 
    public string address {get; set;} 
    public string phone {get; set;} 
    public string email {get; set;} 
    public string descriptionofservice {get; set;} 
    public Decimal  taxableAmount {get; set;}
    public Decimal  CGST {get; set;}
    public Decimal  SGST {get; set;}
    public Decimal  amountInclusiveTaxes {get; set;}
     public string  amountInclusiveTaxesInWords {get; set;}
    
    public CroyezInvoicePDF(ApexPages.StandardController ctrl){
        try{
            id invoId =  ApexPages.currentPage().getParameters().get('Id'); 
            customSettingRec = [SELECT Address__c,Email__c,GSTIN__c,Name__c,PAN__c,CGST_Rate__c,SGST_Rate__c,Phone__c,Corporate_Identity__c,Sac_Code__c FROM Company_Specifications__c limit 1];   
            
            inoviceRec = [ SELECT Due_Date__c ,Name,Opportunity__r.Name,Opportunity__r.Amount,Opportunity__r.Account.Phone,Opportunity__r.Account.Name,Opportunity__r.Account.Email__c,Opportunity__r.Account.BillingCity,Opportunity__r.Account.BillingStreet,
                          Opportunity__r.Account.BillingCountry,Opportunity__r.Account.BillingGeocodeAccuracy,Opportunity__r.Account.BillingLatitude,Opportunity__r.Account.BillingLongitude,Opportunity__r.Account.BillingPostalCode,Opportunity__r.Account.BillingState ,LeadInvoice__c,Opportunity__c,
                          LeadInvoice__r.Name,LeadInvoice__r.Consultation_Fees__c,LeadInvoice__r.Email , LeadInvoice__r.Phone,LeadInvoice__r.Address__c FROM Invoice__c where id =:invoId]; 
            

            String sObjName = inoviceRec.LeadInvoice__c.getSObjectType().getDescribe().getName();
            System.debug('sObjName ::'+sObjName);
            
            if(inoviceRec.Opportunity__c != null){
                system.debug('Inside Opportunity Block');
                // Giving priority to Opportunity
                //oppRec = [Select id ,Amount,(SELECT Product2.Name FROM OpportunityLineItems)   from Opportunity where id =:invoId ];
                name = inoviceRec.Opportunity__r.Account.name;
                address = inoviceRec.Opportunity__r.Account.BillingStreet+',' +inoviceRec.Opportunity__r.Account.BillingCity+  ',' +inoviceRec.Opportunity__r.Account.BillingState+ ',' +inoviceRec.Opportunity__r.Account.BillingPostalCode+ ',' +inoviceRec.Opportunity__r.Account.BillingCountry;
                phone =  inoviceRec.Opportunity__r.Account.Phone;
                email = inoviceRec.Opportunity__r.Account.Email__c;
                descriptionofservice = 'oppRec.Opportunity__r.OpportunityLineItems.Product2.Name';
                taxableAmount = inoviceRec.Opportunity__r.Amount; 
            }else{
                // Giving priority to Lead
                name = inoviceRec.LeadInvoice__r.Name;
                address = inoviceRec.LeadInvoice__r.Address__c;
                phone =  inoviceRec.LeadInvoice__r.Phone;
                email = inoviceRec.LeadInvoice__r.Email;
                descriptionofservice = 'Consultation/Registation Fee'; 
                taxableAmount = inoviceRec.LeadInvoice__r.Consultation_Fees__c;
            }
            
            CGST = taxableAmount * .09;
            SGST = taxableAmount * .09;
			
            amountInclusiveTaxes = taxableAmount + CGST + SGST ;
            amountInclusiveTaxesInWords = ConertAmountIntegerToString.english_number(amountInclusiveTaxes);
        }catch(Exception e){
            System.debug('Error--'+e.getMessage() +' Line No ::'+e.getLineNumber());
        } 
        
    }
    
    
}