force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/LeadInvoice__c.field-meta.xml
<CustomField>
    <fullName>LeadInvoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Realized</fullName>
            </value>
            <value>
                <fullName>Not Realized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoicetriggerHandler.cls
public with sharing class InvoicetriggerHandler {
    static InvoicetriggerHandler InvoicehandlerInstance;

    public static InvoicetriggerHandler getInstance(){
        if (InvoicehandlerInstance == null)
        InvoicehandlerInstance = new InvoicetriggerHandler();
        return InvoicehandlerInstance;
    }

    public void CreateTask_InvoiceRealized(map<Id, Invoice__c> invoiceOldmap, map<id, Invoice__c> inoiceNewMap ){

        List<task> SendEvaluationreportTasksToBEInserted = new List<task>();
        List<task> SendAgreementDocTasksToBEInserted = new List<task>();
        if (!inoiceNewMap.isEmpty()) {
            for (Invoice__c inv : inoiceNewMap.values()) {
                if (inv.Status__c != null && inv.Status__c==Constants.INVOICE_REALIZED && inv.Status__c != invoiceOldmap.get(inv.id).Status__c) {
                    Task tsk = new task();
                    tsk.subject = Constants.SEND_EVALUATION_REPORT;
                    tsk.whoId = inv.LeadInvoice__c;
                    tsk.ownerId = inv.ownerId;
                    tsk.status = 'Open';
                    tsk.Priority = 'High';
                    tsk.ActivityDate = system.today();
                    SendEvaluationreportTasksToBEInserted.add(tsk);


                    tsk.subject = Constants.SEND_AGREEMENT_DOC;
                    SendAgreementDocTasksToBEInserted.add(tsk);

                    
                }
            }


            if (!SendEvaluationreportTasksToBEInserted.isEmpty()) {
                insert SendEvaluationreportTasksToBEInserted;
            }

            if (!SendAgreementDocTasksToBEInserted.isEmpty()) {
                insert SendAgreementDocTasksToBEInserted;
                
            }
            
        }
    }
}