force-app/main/default/objects/Lead/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Consultation_Fees__c.field-meta.xml
<CustomField>
    <fullName>Consultation_Fees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Consultation Fees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/File_Number__c.field-meta.xml
<CustomField>
    <fullName>File_Number__c</fullName>
    <displayFormat>L-{000000}</displayFormat>
    <label>File Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/AgreementPDFClass.cls
public class AgreementPDFClass {
      public Lead leadRec {get; set;} 
      public string name  {get; set;} 
     public string company  {get; set;} 
    public decimal fee  {get; set;} 
    public string email  {get; set;} 
    public string phone  {get; set;} 
     public string address  {get; set;} 
    public AgreementPDFClass(ApexPages.StandardController ctrl){
        try{
           id leadId =  ApexPages.currentPage().getParameters().get('Id'); 
            leadRec = [SELECT Address__c,Company,Consultation_Fees__c,File_Number__c,CreatedDate,Email,FirstName,Phone FROM Lead where id=:leadId];
            name = leadRec.FirstName;
            company = leadRec.Company;
            fee = leadRec.Consultation_Fees__c;
            email = leadRec.Email;
            phone = leadRec.Phone;
            address = leadRec.Address__c;
        } catch(Exception e){
            System.debug('Error--'+e.getMessage() +' Line No ::'+e.getLineNumber());
        } 

    }

}