force-app/main/default/objects/Lead/fields/Answered_Remark__c.field-meta.xml
<CustomField>
    <fullName>Answered_Remark__c</fullName>
    <label>Answered Remark</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Answered_Status__c.field-meta.xml
<CustomField>
    <fullName>Answered_Status__c</fullName>
    <label>Answered Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Call_Status__c.field-meta.xml
<CustomField>
    <fullName>Call_Status__c</fullName>
    <label>Call Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Not Answered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Call_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Call_Sub_Status__c</fullName>
    <label>Call Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>Already A Customer</fullName>
            </value>
            <value>
                <fullName>Invalid Phone Number</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Not Reachable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Demo_Remark__c.field-meta.xml
<CustomField>
    <fullName>Demo_Remark__c</fullName>
    <label>Demo Remark</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Disqualified_Reason__c.field-meta.xml
<CustomField>
    <fullName>Disqualified_Reason__c</fullName>
    <label>Disqualified Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Existing_Customer_Remark__c.field-meta.xml
<CustomField>
    <fullName>Existing_Customer_Remark__c</fullName>
    <label>Existing Customer Remark</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Follow_Up_Comments__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Comments__c</fullName>
    <label>Follow Up Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Follow_Up_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date_Time__c</fullName>
    <label>Follow Up Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/InValid_Remark__c.field-meta.xml
<CustomField>
    <fullName>InValid_Remark__c</fullName>
    <label>Invalid Remark</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Language_Remark__c.field-meta.xml
<CustomField>
    <fullName>Language_Remark__c</fullName>
    <label>Language Remark</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Not_Answered__c.field-meta.xml
<CustomField>
    <fullName>Not_Answered__c</fullName>
    <label>Not Answered</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Temporarily Disconnected</fullName>
            </value>
            <value>
                <fullName>Switch off</fullName>
            </value>
            <value>
                <fullName>Not reachable</fullName>
            </value>
            <value>
                <fullName>Ringing no response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Not_Answered_Remark__c.field-meta.xml
<CustomField>
    <fullName>Not_Answered_Remark__c</fullName>
    <label>Not Answered Remark</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Not_Interested_Reason__c.field-meta.xml
<CustomField>
    <fullName>Not_Interested_Reason__c</fullName>
    <label>Not Interested Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Not_Interested_Remark__c.field-meta.xml
<CustomField>
    <fullName>Not_Interested_Remark__c</fullName>
    <label>Not Interested Remark</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Schedule_Demo_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Demo_Date__c</fullName>
    <label>Schedule Demo Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Temporary_Disconnected_Remark__c.field-meta.xml
<CustomField>
    <fullName>Temporary_Disconnected_Remark__c</fullName>
    <label>Temporary Disconnected Remark</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CallDispositionHelper.cls
public without Sharing class CallDispositionHelper {
    @auraEnabled
    public static void updateLeadDetails(Lead leadRec, string notIntRemarkremark, string disqualifiedRemark){
        try{
            system.debug('leadRec::'+leadRec);
            //leadRec.Answered_Remarks__c = notIntRemarkremark;
            //leadRec.Answered_Remarks__c = disqualifiedRemark;
            update leadRec;
        }catch(exception ex){
            system.debug('Error>>'+ex.getMessage());
            system.debug('Err@@>>'+ex.getLineNumber());
            
        }
    }    
    @auraEnabled
    public static pickValWrap allPickVal(String leadId){
        system.debug('leadId-->'+leadId);
            
        list<string> callStatus = getPickListValuesIntoList('Lead', 'Call_Status__c');
        list<string> notAnswered = getPickListValuesIntoList('Lead', 'Not_Answered__c');
        list<string> answeredStatus = getPickListValuesIntoList('Lead', 'Answered_Status__c');
        list<string> notAnsReasons = getPickListValuesIntoList('Lead', 'Not_Interested_Reason__c');
        list<string> disqualifiedReasons = getPickListValuesIntoList('Lead', 'Disqualified_Reason__c');
        list<string> callSubStatus = getPickListValuesIntoList('Lead', 'Call_Sub_Status__c');
        Lead leadRec = [Select Id,Call_Status__c,Temporary_Disconnected_Remark__c, Not_Answered__c, Not_Interested_Remark__c,Not_Interested_Reason__c,InValid_Remark__c,Language_Remark__c,Not_Answered_Remark__c	,Answered_Status__c,Existing_Customer_Remark__c, Answered_Remark__c,Demo_Remark__c, Disqualified_Reason__c, Schedule_Demo_Date__c,Call_Sub_Status__c, Follow_Up_Date_Time__c,Follow_up_Comments__c from Lead Where Id = : leadId ];
        pickValWrap wrapperInstance = new pickValWrap(callStatus, notAnswered, answeredStatus, notAnsReasons, disqualifiedReasons,callSubStatus, leadRec.Answered_Remark__c, leadRec.Schedule_Demo_Date__c, leadRec.Follow_Up_Date_Time__c, leadRec);
        system.debug('wrapperInstance-->'+wrapperInstance);
        return wrapperInstance;
    }
    @auraEnabled
    public static List<String> getPickListValuesIntoList(String strObjectName, String strPicklistField){
        system.debug('strObjectName::'+strObjectName);
        system.debug('strPicklistField::'+strPicklistField);
        List<String> pickListValuesList= new List<String>();
        Map<String, String> mapPickListValues = new Map<String, String>();
        Schema.SObjectType objSobjectType = Schema.getGlobalDescribe().get(strObjectName);
        Schema.DescribeSObjectResult objDescribeSobject = objSobjectType.getDescribe();
        Map<String, Schema.SObjectField> mapFields = objDescribeSobject.fields.getMap();
        List<Schema.PicklistEntry> lstPickListValues = mapFields.get(strPicklistField).getDescribe().getPickListValues();
        for( Schema.PicklistEntry pickListVal : lstPickListValues){
            pickListValuesList.add(pickListVal.getLabel());
        }
        system.debug('pickListValuesList::>'+pickListValuesList);
        return pickListValuesList;
    }
    public class pickValWrap{
        @auraEnabled
        public list<string> callStatus;
        @auraEnabled
        public list<string> notAnswered;
        @auraEnabled
        public list<string> answeredStatus;
        @auraEnabled
        public list<string> notAnsReasons;
        @auraEnabled
        public list<string> disqualifiedReasons;
        @auraEnabled
        public list<string> callSubStatus;
        @auraEnabled
        public string remarks;
        @auraEnabled
        public datetime scheduledatetime;
        @auraEnabled
        public datetime followUpDateTime;
        @auraEnabled
        public Lead leadRec;
        
        public pickValWrap(list<string> callStatus, list<string> notAnswered, list<string> answeredStatus, list<string> notAnsReasons,list<string> disqualifiedReasons,list<string> callSubStatus, string remarks, datetime scheduledatetime, datetime followUpDateTime, Lead leadRec){
            this.callStatus = callStatus;
            this.notAnswered = notAnswered;
            this.answeredStatus = answeredStatus;
            this.notAnsReasons = notAnsReasons;
            this.disqualifiedReasons= disqualifiedReasons;
            this.callSubStatus = callSubStatus;
            this.remarks = remarks;
            this.scheduledatetime = scheduledatetime; 
            this.followUpDateTime = followUpDateTime;
            this.leadRec = leadRec;
        }
    }
}