force-app/main/default/objects/Lead/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>Prospect__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Visa_Type__c.field-meta.xml
<CustomField>
    <fullName>Visa_Type__c</fullName>
    <label>Visa Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Study</fullName>
            </value>
            <value>
                <fullName>TRV</fullName>
            </value>
            <value>
                <fullName>PRV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prospect__c/Prospect__c.object-meta.xml
<CustomObject>
    <label>Prospect</label>
    <nameField>
        <label>Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect__c/fields/IsQualified__c.field-meta.xml
<CustomField>
    <fullName>IsQualified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsQualified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Prospect__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prospect__c/fields/Visa_Type__c.field-meta.xml
<CustomField>
    <fullName>Visa_Type__c</fullName>
    <label>Visa Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Study</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Permanent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProspectTriggerHandler.cls
public class ProspectTriggerHandler {
    public static void beforeUpdate(map<Id,Prospect__c> newmapProspect , map<Id,Prospect__c> oldmapProspect){
        for(Prospect__c pro :newmapProspect.values()){
            if(pro.Stage__c != oldmapProspect.get(pro.id).Stage__c && pro.Stage__c != null && pro.Stage__c == 'Qualified' && pro.IsQualified__c == false  ){
                pro.IsQualified__c = True;
            }
        }        
    } 
    public static void afterUpdate(map<Id,Prospect__c> newmapProspect , map<Id,Prospect__c> oldmapProspect){
        Database.DMLOptions dmo = new Database.DMLOptions();
		dmo.assignmentRuleHeader.useDefaultRule = true;
        List<Lead> leadlist = new List<Lead>();
        for(Prospect__c prospectRec : newmapProspect.values())
        {
            system.debug('oldmapProspect.get(prospectRec.id).IsQualified__c--->'+oldmapProspect.get(prospectRec.id).IsQualified__c);
            system.debug('prospectRec.IsQualified__c-->'+prospectRec.IsQualified__c);
            if (prospectRec.Stage__c != oldmapProspect.get(prospectRec.id).Stage__c && prospectRec.Stage__c != null && prospectRec.Stage__c == 'Qualified' &&  prospectRec.IsQualified__c != oldmapProspect.get(prospectRec.id).IsQualified__c  &&  prospectRec.IsQualified__c !=null && prospectRec.IsQualified__c == true){
                Lead leadRec = new Lead();
                leadRec.Prospect__c= prospectRec.Id;
                leadRec.LastName =   prospectRec.Name;
                leadRec.Company = prospectRec.Company__c;
                leadRec.Status = 'New';
                leadRec.Visa_Type__c = prospectRec.Visa_Type__c;
                leadRec.Email = prospectRec.Email__c;
                leadRec.Phone = prospectRec.Phone__c;
                leadRec.setOptions(dmo);
                leadlist.add(leadRec);  
                
        
                
            }
        }
        insert leadlist;
        
    }
}